<?php

namespace Database\Seeders;

use App\Models\Peta;
use App\Models\UnitKerja;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PetaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $petaData = [
            // Data tahun 2020
            [
                'jenis' => 'WADIR I',
                'judul' => 'Pengembangan Kurikulum Berbasis Kompetensi',
                'kode_regist' => 'WADIR I_2020_1',
                'anggaran' => 120000000,
                'pernyataan' => 'Risiko kurangnya kompetensi dosen dalam kurikulum baru',
                'kategori' => 'SDM',
                'uraian' => 'Kurangnya pelatihan dapat menghambat implementasi kurikulum',
                'metode' => 'Pelatihan dan workshop berkala untuk dosen',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 3,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2020-03-15',
                'waktu_telaah_teknis' => '2020-03-20',
                'waktu_telaah_spi' => '2020-03-25',
                'created_at' => '2020-01-15',
                'updated_at' => '2020-03-25',
            ],
            [
                'jenis' => 'BPKU',
                'judul' => 'Persiapan Akreditasi Institusi',
                'kode_regist' => 'BPKU_2020_1',
                'anggaran' => 200000000,
                'pernyataan' => 'Risiko ketidaklengkapan dokumen akreditasi',
                'kategori' => 'Mutu',
                'uraian' => 'Dokumen yang tidak lengkap dapat menunda proses akreditasi',
                'metode' => 'Tim khusus penyiapan dokumen akreditasi',
                'skor_kemungkinan' => 4,
                'skor_dampak' => 5,
                'tingkat_risiko' => 'High',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2020-02-10',
                'waktu_telaah_teknis' => '2020-02-15',
                'waktu_telaah_spi' => '2020-02-20',
                'created_at' => '2020-01-20',
                'updated_at' => '2020-02-20',
            ],
            [
                'jenis' => 'UPA TIK',
                'judul' => 'Migrasi ke Cloud Computing',
                'kode_regist' => 'UPA TIK_2020_1',
                'anggaran' => 350000000,
                'pernyataan' => 'Risiko kehilangan data saat migrasi',
                'kategori' => 'Teknologi',
                'uraian' => 'Proses migrasi yang tidak hati-hati dapat menyebabkan data loss',
                'metode' => 'Backup data dan testing sebelum migrasi',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 5,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'created_at' => '2020-02-01',
                'updated_at' => '2020-05-15',
            ],

            // Data tahun 2021
            [
                'jenis' => 'WADIR I',
                'judul' => 'Implementasi Pembelajaran Hybrid',
                'kode_regist' => 'WADIR I_2021_1',
                'anggaran' => 180000000,
                'pernyataan' => 'Risiko ketidaksiapan infrastruktur pembelajaran hybrid',
                'kategori' => 'Pembelajaran',
                'uraian' => 'Infrastruktur yang tidak memadai menghambat pembelajaran efektif',
                'metode' => 'Pengadaan peralatan dan pelatihan SDM',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2021-03-10',
                'waktu_telaah_teknis' => '2021-03-15',
                'waktu_telaah_spi' => '2021-03-20',
                'created_at' => '2021-01-10',
                'updated_at' => '2021-03-20',
            ],
            [
                'jenis' => 'WADIR II',
                'judul' => 'Program Penelitian Kolaboratif Nasional',
                'kode_regist' => 'WADIR II_2021_1',
                'anggaran' => 250000000,
                'pernyataan' => 'Risiko kurangnya publikasi jurnal internasional',
                'kategori' => 'Penelitian',
                'uraian' => 'Target publikasi tidak tercapai dapat mengurangi penilaian penelitian',
                'metode' => 'Pendampingan penulisan jurnal internasional',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'created_at' => '2021-02-01',
                'updated_at' => '2021-06-30',
            ],
            [
                'jenis' => 'WADIR III',
                'judul' => 'Pengembangan Program Magang Industri',
                'kode_regist' => 'WADIR III_2021_1',
                'anggaran' => 150000000,
                'pernyataan' => 'Risiko kurangnya mitra industri untuk magang',
                'kategori' => 'Kemitraan',
                'uraian' => 'Keterbatasan mitra dapat mengurangi kesempatan magang mahasiswa',
                'metode' => 'Penjajakan kerjasama dengan industri baru',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 3,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2021-03-15',
                'updated_at' => '2021-08-20',
            ],

            // Data tahun 2022
            [
                'jenis' => 'WADIR IV',
                'judul' => 'Renovasi Gedung Perkuliahan',
                'kode_regist' => 'WADIR IV_2022_1',
                'anggaran' => 800000000,
                'pernyataan' => 'Risiko keterlambatan proyek renovasi',
                'kategori' => 'Infrastruktur',
                'uraian' => 'Keterlambatan dapat mengganggu jadwal perkuliahan',
                'metode' => 'Monitoring ketat progres renovasi',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2022-02-10',
                'waktu_telaah_teknis' => '2022-02-15',
                'waktu_telaah_spi' => '2022-02-20',
                'created_at' => '2022-01-05',
                'updated_at' => '2022-02-20',
            ],
            [
                'jenis' => 'SPI',
                'judul' => 'Implementasi Sistem Audit Digital',
                'kode_regist' => 'SPI_2022_1',
                'anggaran' => 150000000,
                'pernyataan' => 'Risiko resistensi pengguna terhadap sistem baru',
                'kategori' => 'Sistem Informasi',
                'uraian' => 'Penolakan pengguna dapat menghambat efektivitas audit',
                'metode' => 'Sosialisasi dan pelatihan sistem audit digital',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 3,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2022-03-01',
                'updated_at' => '2022-07-15',
            ],
            [
                'jenis' => 'Jurusan Teknik Elektro',
                'judul' => 'Pengadaan Alat Lab IoT',
                'kode_regist' => 'Jurusan Teknik Elektro_2022_1',
                'anggaran' => 300000000,
                'pernyataan' => 'Risiko alat tidak sesuai spesifikasi',
                'kategori' => 'Pengadaan',
                'uraian' => 'Alat yang tidak sesuai dapat menghambat praktikum',
                'metode' => 'Verifikasi vendor dan spesifikasi teknis detail',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2022-04-10',
                'updated_at' => '2022-09-30',
            ],

            // Data tahun 2023
            [
                'jenis' => 'BAK',
                'judul' => 'Integrasi Sistem Informasi Akademik',
                'kode_regist' => 'BAK_2023_1',
                'anggaran' => 400000000,
                'pernyataan' => 'Risiko downtime sistem saat integrasi',
                'kategori' => 'Sistem Informasi',
                'uraian' => 'Downtime dapat mengganggu proses akademik',
                'metode' => 'Implementasi bertahap dengan backup system',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2023-02-15',
                'waktu_telaah_teknis' => '2023-02-20',
                'waktu_telaah_spi' => '2023-02-25',
                'created_at' => '2023-01-10',
                'updated_at' => '2023-02-25',
            ],
            [
                'jenis' => 'Jurusan Teknologi Informasi',
                'judul' => 'Program Sertifikasi Internasional Mahasiswa',
                'kode_regist' => 'Jurusan Teknologi Informasi_2023_1',
                'anggaran' => 200000000,
                'pernyataan' => 'Risiko rendahnya partisipasi mahasiswa',
                'kategori' => 'Pembelajaran',
                'uraian' => 'Partisipasi rendah dapat mengurangi efektivitas program',
                'metode' => 'Sosialisasi intensif dan insentif untuk peserta',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 3,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2023-03-01',
                'updated_at' => '2023-08-30',
            ],
            [
                'jenis' => 'UPA Perpustakaan',
                'judul' => 'Langganan Database Jurnal Internasional',
                'kode_regist' => 'UPA Perpustakaan_2023_1',
                'anggaran' => 180000000,
                'pernyataan' => 'Risiko rendahnya utilisasi database',
                'kategori' => 'Sumber Daya',
                'uraian' => 'Rendahnya penggunaan mengurangi ROI investasi',
                'metode' => 'Pelatihan literasi digital dan promosi database',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 3,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'created_at' => '2023-02-15',
                'updated_at' => '2023-10-20',
            ],

            // Data tahun 2024
            [
                'jenis' => 'WADIR I',
                'judul' => 'Pengembangan Kurikulum Merdeka Belajar',
                'kode_regist' => 'WADIR I_2024_1',
                'anggaran' => 220000000,
                'pernyataan' => 'Risiko ketidaksesuaian dengan regulasi baru',
                'kategori' => 'Regulasi',
                'uraian' => 'Kurikulum yang tidak sesuai dapat menghambat akreditasi',
                'metode' => 'Review dan adjustment kurikulum berkelanjutan',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2024-03-05',
                'waktu_telaah_teknis' => '2024-03-10',
                'waktu_telaah_spi' => '2024-03-15',
                'created_at' => '2024-01-15',
                'updated_at' => '2024-03-15',
            ],
            [
                'jenis' => 'WADIR II',
                'judul' => 'Hibah Penelitian Kompetitif',
                'kode_regist' => 'WADIR II_2024_1',
                'anggaran' => 500000000,
                'pernyataan' => 'Risiko kegagalan kompetisi hibah penelitian',
                'kategori' => 'Pendanaan',
                'uraian' => 'Proposal yang ditolak mengurangi dana penelitian',
                'metode' => 'Pendampingan penulisan proposal penelitian',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'created_at' => '2024-02-01',
                'updated_at' => '2024-11-30',
            ],
            [
                'jenis' => 'WADIR III',
                'judul' => 'Program Link and Match dengan DUDI',
                'kode_regist' => 'WADIR III_2024_1',
                'anggaran' => 300000000,
                'pernyataan' => 'Risiko mismatch kebutuhan industri dengan kurikulum',
                'kategori' => 'Kemitraan',
                'uraian' => 'Ketidaksesuaian dapat mengurangi daya serap lulusan',
                'metode' => 'FGD rutin dengan stakeholder industri',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2024-03-10',
                'updated_at' => '2024-12-15',
            ],
            [
                'jenis' => 'UPA TIK',
                'judul' => 'Implementasi Keamanan Siber Tingkat Lanjut',
                'kode_regist' => 'UPA TIK_2024_1',
                'anggaran' => 450000000,
                'pernyataan' => 'Risiko serangan siber dan ransomware',
                'kategori' => 'Keamanan',
                'uraian' => 'Serangan dapat melumpuhkan sistem informasi kampus',
                'metode' => 'Implementasi firewall, IDS/IPS, dan backup berkala',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 5,
                'tingkat_risiko' => 'High',
                'status_telaah' => 1,
                'created_at' => '2024-01-20',
                'updated_at' => '2024-08-30',
            ],

            // Data tahun 2025
            [
                'jenis' => 'BPKU',
                'judul' => 'Reakreditasi Program Studi Unggulan',
                'kode_regist' => 'BPKU_2025_1',
                'anggaran' => 250000000,
                'pernyataan' => 'Risiko penurunan peringkat akreditasi',
                'kategori' => 'Mutu',
                'uraian' => 'Penurunan peringkat dapat mengurangi daya saing prodi',
                'metode' => 'Perbaikan dokumen dan peningkatan kinerja prodi',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 5,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2025-02-20',
                'waktu_telaah_teknis' => '2025-02-25',
                'waktu_telaah_spi' => '2025-03-01',
                'created_at' => '2025-01-15',
                'updated_at' => '2025-03-01',
            ],
            [
                'jenis' => 'Jurusan Teknik Mesin',
                'judul' => 'Pengembangan Lab Manufaktur Modern',
                'kode_regist' => 'Jurusan Teknik Mesin_2025_1',
                'anggaran' => 600000000,
                'pernyataan' => 'Risiko ketidaksesuaian peralatan dengan kebutuhan industri',
                'kategori' => 'Fasilitas',
                'uraian' => 'Peralatan yang tidak update mengurangi kompetensi lulusan',
                'metode' => 'Survey kebutuhan industri dan konsultasi ahli',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2025-02-10',
                'updated_at' => '2025-11-30',
            ],
            [
                'jenis' => 'SPI',
                'judul' => 'Audit Keuangan dan Operasional',
                'kode_regist' => 'SPI_2025_1',
                'anggaran' => 180000000,
                'pernyataan' => 'Risiko temuan audit yang signifikan',
                'kategori' => 'Pengendalian Internal',
                'uraian' => 'Temuan signifikan dapat mempengaruhi citra institusi',
                'metode' => 'Penguatan internal control dan SOP',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'created_at' => '2025-03-01',
                'updated_at' => '2025-12-15',
            ],

            // Data tahun 2026 (existing + new)
            [
                'jenis' => 'WADIR I',
                'judul' => 'Pengembangan Kurikulum Berbasis Industri 4.0',
                'kode_regist' => 'WADIR I_1',
                'anggaran' => 150000000,
                'pernyataan' => 'Risiko ketidaksesuaian kurikulum dengan kebutuhan industri',
                'kategori' => 'Strategis',
                'uraian' => 'Kurikulum yang tidak relevan dapat menyebabkan lulusan kurang kompetitif',
                'metode' => 'Review berkala dengan stakeholder industri',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2026-01-05',
                'waktu_telaah_teknis' => '2026-01-10',
                'waktu_telaah_spi' => '2026-01-15',
            ],
            [
                'jenis' => 'WADIR I',
                'judul' => 'Peningkatan Kualitas Pembelajaran Digital',
                'kode_regist' => 'WADIR I_2',
                'anggaran' => 200000000,
                'pernyataan' => 'Risiko kegagalan implementasi sistem pembelajaran online',
                'kategori' => 'Operasional',
                'uraian' => 'Infrastruktur IT yang kurang memadai dapat menghambat pembelajaran',
                'metode' => 'Peningkatan kapasitas server dan bandwidth',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 3,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 0,
            ],
            [
                'jenis' => 'WADIR II',
                'judul' => 'Pengembangan Penelitian Kolaboratif',
                'kode_regist' => 'WADIR II_1',
                'anggaran' => 300000000,
                'pernyataan' => 'Risiko keterlambatan publikasi penelitian internasional',
                'kategori' => 'Akademik',
                'uraian' => 'Keterlambatan dapat mengurangi reputasi institusi',
                'metode' => 'Monitoring progres penelitian secara berkala',
                'skor_kemungkinan' => 3,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2026-01-06',
                'waktu_telaah_teknis' => '2026-01-12',
                'waktu_telaah_spi' => '2026-01-18',
            ],
            [
                'jenis' => 'WADIR III',
                'judul' => 'Program Kerjasama Industri',
                'kode_regist' => 'WADIR III_1',
                'anggaran' => 250000000,
                'pernyataan' => 'Risiko pembatalan MoU dengan mitra industri',
                'kategori' => 'Kemitraan',
                'uraian' => 'Pembatalan dapat mengurangi peluang magang mahasiswa',
                'metode' => 'Evaluasi berkala kepuasan mitra',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 4,
                'tingkat_risiko' => 'Low',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2026-01-07',
                'waktu_telaah_teknis' => '2026-01-14',
                'waktu_telaah_spi' => '2026-01-20',
            ],
            [
                'jenis' => 'BPKU',
                'judul' => 'Peningkatan Layanan Penjaminan Mutu',
                'kode_regist' => 'BPKU_1',
                'anggaran' => 100000000,
                'pernyataan' => 'Risiko penurunan nilai akreditasi',
                'kategori' => 'Mutu',
                'uraian' => 'Penurunan akreditasi dapat mengurangi minat calon mahasiswa',
                'metode' => 'Audit mutu internal berkala',
                'skor_kemungkinan' => 2,
                'skor_dampak' => 5,
                'tingkat_risiko' => 'Moderate',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2026-01-08',
                'waktu_telaah_teknis' => '2026-01-15',
                'waktu_telaah_spi' => '2026-01-22',
            ],
            [
                'jenis' => 'UPA TIK',
                'judul' => 'Upgrade Infrastruktur Jaringan Kampus',
                'kode_regist' => 'UPA TIK_1',
                'anggaran' => 600000000,
                'pernyataan' => 'Risiko gangguan jaringan internet kampus',
                'kategori' => 'Infrastruktur IT',
                'uraian' => 'Gangguan dapat menghambat aktivitas akademik',
                'metode' => 'Redundancy system dan backup connection',
                'skor_kemungkinan' => 4,
                'skor_dampak' => 5,
                'tingkat_risiko' => 'Extreme',
                'status_telaah' => 1,
                'waktu_telaah_subtansi' => '2026-01-09',
                'waktu_telaah_teknis' => '2026-01-16',
                'waktu_telaah_spi' => '2026-01-23',
            ],
        ];

        foreach ($petaData as $peta) {
            Peta::create($peta);
        }
    }
}
